-- Drop tables in reverse order to ensure constraints don't throw errors

DROP TABLE IF EXISTS BILL_DISCOUNT CASCADE;
DROP TABLE IF EXISTS PAYMENT CASCADE;
DROP TABLE IF EXISTS BILL CASCADE;
DROP TABLE IF EXISTS ORDER_ITEM CASCADE;
DROP TABLE IF EXISTS "ORDER" CASCADE;
DROP TABLE IF EXISTS DISCOUNT CASCADE;
