-- =============================================
-- SELECT 1a: Orders with their bill and payment info (using JOIN)
-- Retrieves all orders along with their total amount, tax, and payment method.
-- Uses explicit JOINs between ORDER, BILL and PAYMENT.
-- Sorted by total amount (highest first).
-- =============================================
SELECT o.order_id, o.order_status, o.order_time,
       b.total_amount, b.tax, p.payment_method
FROM "ORDER" o
JOIN BILL b ON o.order_id = b.order_id
JOIN PAYMENT p ON b.bill_id = p.bill_id
ORDER BY b.total_amount DESC;


-- =============================================
-- SELECT 1b: Orders with their bill and payment info (using subqueries)
-- Same result as 1a but uses correlated subqueries instead of JOINs
-- to fetch total_amount, tax, and payment_method for each order.
-- =============================================
SELECT o.order_id, o.order_status, o.order_time,
       (SELECT b.total_amount FROM BILL b WHERE b.order_id = o.order_id) AS total_amount,
       (SELECT b.tax FROM BILL b WHERE b.order_id = o.order_id) AS tax,
       (SELECT p.payment_method FROM PAYMENT p 
        JOIN BILL b ON p.bill_id = b.bill_id 
        WHERE b.order_id = o.order_id LIMIT 1) AS payment_method
FROM "ORDER" o
ORDER BY total_amount DESC;


-- =============================================
-- SELECT 2a: Bills with applied discounts and savings amount (using JOIN)
-- Shows each bill that has a discount applied, the discount name/percentage,
-- and the actual money saved (calculated as total * percentage / 100).
-- Sorted by savings amount (highest first).
-- =============================================
SELECT b.bill_id, b.total_amount, 
       d.discount_name, d.percentage,
       ROUND(b.total_amount * d.percentage / 100, 2) AS amount_saved
FROM BILL b
JOIN BILL_DISCOUNT bd ON b.bill_id = bd.bill_id
JOIN DISCOUNT d ON bd.discount_id = d.discount_id
ORDER BY amount_saved DESC;

-- =============================================
-- SELECT 2b: Bills with applied discounts and savings amount (using EXISTS)
-- Same result as 2a but uses EXISTS subquery instead of JOIN
-- to verify the link between a bill and a discount exists.
-- =============================================
SELECT b.bill_id, b.total_amount,
       d.discount_name, d.percentage,
       ROUND(b.total_amount * d.percentage / 100, 2) AS amount_saved
FROM BILL b, BILL_DISCOUNT bd, DISCOUNT d
WHERE EXISTS (
    SELECT 1 FROM BILL_DISCOUNT bd2 
    WHERE bd2.bill_id = b.bill_id AND bd2.discount_id = d.discount_id
)
AND bd.bill_id = b.bill_id AND bd.discount_id = d.discount_id
ORDER BY amount_saved DESC;


-- =============================================
-- SELECT 3a: Revenue and order count per waiter per month (using JOIN + GROUP BY)
-- Aggregates the number of orders and total revenue generated by each waiter,
-- grouped by year and month. Sorted chronologically, then by order count.
-- =============================================
SELECT o.waiter_id,
       EXTRACT(YEAR FROM o.order_time) AS year,
       EXTRACT(MONTH FROM o.order_time) AS month,
       COUNT(o.order_id) AS total_orders,
       SUM(b.total_amount) AS total_revenue
FROM "ORDER" o
JOIN BILL b ON o.order_id = b.order_id
GROUP BY o.waiter_id, EXTRACT(YEAR FROM o.order_time), EXTRACT(MONTH FROM o.order_time)
ORDER BY year, month, total_orders DESC;

-- =============================================
-- SELECT 3b: Revenue and order count per waiter per month (using subquery)
-- Same result as 3a but uses a subquery to pre-build the flat dataset
-- before applying GROUP BY aggregation on top.
-- =============================================
SELECT waiter_id, year, month,
       COUNT(*) AS total_orders,
       SUM(total_amount) AS total_revenue
FROM (
    SELECT o.waiter_id, o.order_id,
           EXTRACT(YEAR FROM o.order_time) AS year,
           EXTRACT(MONTH FROM o.order_time) AS month,
           b.total_amount
    FROM "ORDER" o
    JOIN BILL b ON o.order_id = b.order_id
) AS sub
GROUP BY waiter_id, year, month
ORDER BY year, month, total_orders DESC;


-- =============================================
-- SELECT 4a: Payment method usage and revenue per month (using JOIN)
-- Counts how many times each payment method was used per month,
-- and the total amount collected with that method.
-- Sorted chronologically, then by usage count.
-- =============================================
SELECT p.payment_method,
       EXTRACT(YEAR FROM p.payment_time) AS year,
       EXTRACT(MONTH FROM p.payment_time) AS month,
       COUNT(p.payment_id) AS usage_count,
       SUM(p.amount) AS total_paid
FROM PAYMENT p
JOIN BILL b ON p.bill_id = b.bill_id
GROUP BY p.payment_method, EXTRACT(YEAR FROM p.payment_time), EXTRACT(MONTH FROM p.payment_time)
ORDER BY year, month, usage_count DESC;

-- =============================================
-- SELECT 4b: Payment method usage and revenue per month (using subquery + IN)
-- Same result as 4a but filters payments using IN (subquery on BILL)
-- instead of a JOIN, then aggregates with GROUP BY.
-- =============================================
SELECT payment_method, year, month,
       COUNT(*) AS usage_count,
       SUM(amount) AS total_paid
FROM (
    SELECT p.payment_method, p.amount,
           EXTRACT(YEAR FROM p.payment_time) AS year,
           EXTRACT(MONTH FROM p.payment_time) AS month
    FROM PAYMENT p
    WHERE p.bill_id IN (SELECT bill_id FROM BILL)
) AS sub
GROUP BY payment_method, year, month
ORDER BY year, month, usage_count DESC;

-- =============================================
-- SELECT 5: Orders that have special requests
-- Retrieves all order items that include a special request (e.g. allergies, preferences).
-- Joins ORDER and ORDER_ITEM, filters where special_request is not empty.
-- Sorted by order date (most recent first).
-- =============================================
SELECT o.order_id, o.order_time, o.order_status,
       oi.menu_item_id, oi.quantity, oi.special_request
FROM "ORDER" o
JOIN ORDER_ITEM oi ON o.order_id = oi.order_id
WHERE oi.special_request IS NOT NULL
ORDER BY o.order_time DESC;

-- =============================================
-- SELECT 6: Daily billing summary
-- Groups all bills by day, showing the number of bills issued,
-- total revenue and total tax collected per day.
-- Sorted from most recent day to oldest.
-- =============================================
SELECT EXTRACT(DAY FROM b.bill_time) AS day,
       EXTRACT(MONTH FROM b.bill_time) AS month,
       EXTRACT(YEAR FROM b.bill_time) AS year,
       COUNT(b.bill_id) AS nb_bills,
       SUM(b.total_amount) AS daily_revenue,
       SUM(b.tax) AS daily_tax
FROM BILL b
GROUP BY EXTRACT(YEAR FROM b.bill_time), 
         EXTRACT(MONTH FROM b.bill_time), 
         EXTRACT(DAY FROM b.bill_time)
ORDER BY year DESC, month DESC, day DESC

-- =============================================
-- SELECT 7: Cancelled orders with their items
-- Lists all orders that were cancelled, along with the menu items
-- and quantities that were part of those orders.
-- Sorted by order date (most recent first).
-- =============================================
SELECT o.order_id, o.order_time, o.waiter_id,
       oi.menu_item_id, oi.quantity,
       EXTRACT(YEAR FROM o.order_time) AS annee,
       EXTRACT(MONTH FROM o.order_time) AS mois
FROM "ORDER" o
JOIN ORDER_ITEM oi ON o.order_id = oi.order_id
WHERE o.order_status = 'Cancelled'
ORDER BY o.order_time DESC;

-- =============================================
-- SELECT 8: All discounts sorted by percentage
-- Lists every discount with its validity period and duration in days.
-- Sorted by discount percentage (highest first).
-- =============================================
SELECT d.discount_id, d.discount_name, d.percentage,
       d.valid_from, d.valid_to,
       (d.valid_to - d.valid_from) AS duree_jours
FROM DISCOUNT d
ORDER BY d.percentage DESC;


-- DELETE 1: Remove payments with an amount below 5€
-- These are considered data entry errors (no realistic payment should be this low).
DELETE FROM PAYMENT
WHERE amount < 5;

-- DELETE 2: Remove discounts that expired more than 22 months ago
-- Keeps the DISCOUNT table clean by purging outdated promotional records.
DELETE FROM DISCOUNT
WHERE valid_to < CURRENT_DATE - INTERVAL '22 months';

-- DELETE 3: Remove cancelled orders that never generated a bill
-- These orders were cancelled before any billing occurred, so they hold no financial data.
-- Uses a subquery to ensure we only delete orders with no matching entry in BILL.
DELETE FROM "ORDER"
WHERE order_status = 'Cancelled'
  AND order_id NOT IN (SELECT order_id FROM BILL);

-- UPDATE 1: Automatically cancel orders that have been 'Pending' for more than 2 hours
-- If an order is still pending after 2 hours, it is likely abandoned or stuck.
-- This keeps the system consistent by avoiding indefinitely pending orders.
UPDATE "ORDER"
SET order_status = 'Cancelled'
WHERE order_status = 'Pending'
  AND order_time < NOW() - INTERVAL '2 hours';

-- UPDATE 2: Shift all order times forward by 1 day
-- Can be used to correct a bulk data entry error where dates were off by one day.
UPDATE "ORDER"
SET order_time = order_time + INTERVAL '1 day'
RETURNING *;

-- UPDATE 3: Extend discount validity by 1 month
-- Useful when a promotion campaign needs to be prolonged globally.
UPDATE DISCOUNT
SET valid_to = valid_to + INTERVAL '1 month'
RETURNING *;